version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_USER=sonar
    volumes:
      - postgresdata:/var/lib/postgresql/data
#     - $DIR_CURSO_JENKINS/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  jenkins-master:
    image: jenkins/jenkins:lts-alpine
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $DIR_CURSO_JENKINS/jenkins-docker:/var/jenkins_home
    environment:
      - "JAVA_OPTS=-Xmx1024m" 
  jenkins-slave:
    image: jenkins/ssh-slave
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - $DIR_CURSO_JENKINS/jenkins-docker-slave:/var/jenkins_home      
  sonar-qube:
    image: sonarqube:alpine
    volumes:
      - $DIR_CURSO_JENKINS/sonarqube/conf:/opt/sonarqube/conf
      - $DIR_CURSO_JENKINS/sonarqube/extensions:/opt/sonarqube/extensions
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db/sonar
    ports:
      - "9000:9000" 
      - "9092:9092"
    depends_on:
      - db
volumes:
  postgresdata: